before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: terraform-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.Version={{ .Summary }}"

  - id: terraform-exporter-macos
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - "-s -w -X main.Version={{ .Summary }}"

universal_binaries:
  - ids:
      - terraform-exporter-macos
    replace: true

archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  disable: true

signs:
  - signature: "${artifact}.dmg"
    ids:
      - terraform-exporter-macos
    cmd: gon
    args:
      - .gon-config.hcl
    artifacts: all

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "README"

brews:
  - name: "terraform-exporter"
    tap:
      owner: gideaworx
      name: homebrew-tap
    folder: Formula
    
    commit_author:
      name: goreleaserbot
      email: goreleaser@gideaworx.io

    dependencies:
      - name: nodejs
        type: optional
      - name: openjdk@17
        type: optional
      - name: python3
        type: optional

    description: Export artifacts to terraform files
    license: "MIT"
    test: |
      system "#{bin}/terraform-exporter", "--version"


# The lines beneath this are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
